site_name: py-simple-wrap
site_description: A beginner-friendly Python wrapper package
site_url: https://sara-czasak.github.io/py-simple-wrap/docs/
repo_url: https://github.com/sara-czasak/py-simple-wrap
repo_name: sara-czasak/py-simple-wrap

theme:
  name: material
  palette:
    primary: indigo
  features:
    - content.code.copy

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [py_simple_package/src]
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Tutorial:
      - Module Tutorials:
        - Quickstart: tutorial/quickstart.md
        - Easy Async: tutorial/easy_async.md
        - Easy Archive: tutorial/easy_archive.md
        - Easy Colors: tutorial/easy_colors.md
        - Easy Config: tutorial/easy_config.md
        - Easy Converter: tutorial/easy_converter.md
        - Easy Csv: tutorial/easy_csv.md
        - Easy Data Visualization: tutorial/easy_data_visualization.md
        - Easy Date Formatter: tutorial/easy_date_formatter.md
        - Easy Dict: tutorial/easy_dict.md
        - Easy Flow: tutorial/easy_flow.md
        - Easy File Manager: tutorial/easy_file_manager.md
        - Easy Game: tutorial/easy_game.md
        - Easy Generator: tutorial/easy_generator.md
        - Easy Images: tutorial/easy_images.md
        - Easy Json:
            - Tutorial 1: tutorial/easy_json.md
            - Tutorial 2: tutorial/easy_json2.md
        - Easy Lists: tutorial/easy_lists.md
        - Easy Math:
            - Tutorial 1: tutorial/easy_math.md
            - Tutorial 2: tutorial/easy_math2.md
        - Easy Numbers:
            - Tutorial 1: tutorial/easy_numbers.md
            - Tutorial 2: tutorial/easy_numbers2.md
        - Easy Random: tutorial/easy_random.md
        - Easy Regex: tutorial/easy_regex.md
        - Easy Stats: tutorial/easy_stats.md
        - Easy Strings: tutorial/easy_strings.md
        - Easy Text: tutorial/easy_text.md
        - Easy Validator: tutorial/easy_validator.md
        - Easy Web: tutorial/easy_web.md
      - Project-Based Tutorials:
          - Mystery Number Quest: tutorial/easy_random_game_project.md
  - How To:
      - Contributing: how-to/contributing.md
  - Contributor Hub:
      - Overview: contributor-hub/index.md
      - Docstring Template: contributor-hub/docstring_template.md
      - Tutorial Template: contributor-hub/tutorial_template.md
      - Custom Exception Template: contributor-hub/error_template.md
  - Reference:
      - Easy Archive: reference/easy_archive.md
      - Easy Async: reference/easy_async.md
      - Easy Colors: reference/easy_colors.md
      - Easy Config: reference/easy_config.md
      - Easy Converter: reference/easy_converter.md
      - Easy CSV: reference/easy_csv.md
      - Easy Data Visualization: reference/easy_data_visualization.md
      - Easy Date Formatter: reference/easy_date_formatter.md
      - Easy Dict: reference/easy_dict.md
      - Easy File Manager: reference/easy_file_manager.md
      - Easy Flow: reference/easy_flow.md
      - Easy Game: reference/easy_game
      - Easy Generator: reference/easy_generator.md
      - Easy Images: reference/easy_images.md
      - Easy Json: reference/easy_json.md
      - Easy Lists: reference/easy_lists.md
      - Easy Math: reference/easy_math.md
      - Easy Numbers: reference/easy_numbers.md
      - Easy Random: reference/easy_random.md
      - Easy Regex: reference/easy_regex.md
      - Easy Stats: reference/easy_stats.md
      - Easy Strings: reference/easy_strings.md
      - Easy Text: reference/easy_text.md
      - Easy Validator: reference/easy_validator.md
      - Easy Web: reference/easy_web.md
      - Easy SQL: reference/easy_sql.md
  - About:
      - README: readme.md
      - Contributors: about/contributors.md
      - License: about/license.md
